In [18]:
import numpy as np

In [19]:
data = np.random.randn(7,4)
dot = np.dot
print(data)

[[ 0.01040341 -1.12108213  0.91491158 -0.8213983 ]
 [ 1.17668572 -0.76124686 -0.62372807 -1.51805804]
 [-0.4330706   1.53910055  0.67839033  0.24117016]
 [-0.62031944 -0.20850216 -0.55837277  2.36505763]
 [ 0.26202877  0.87039664 -0.50248578  0.51390909]
 [ 0.3097436  -0.46766453 -0.04054071  0.76477119]
 [-0.39138795 -0.23818194  1.25928933  0.48848648]]


In [20]:
print(data<0)

[[False  True False  True]
 [False  True  True  True]
 [ True False False False]
 [ True  True  True False]
 [False False  True False]
 [False  True  True False]
 [ True  True False False]]


In [21]:
data[data<0] = 0
print(data)

[[ 0.01040341  0.          0.91491158  0.        ]
 [ 1.17668572  0.          0.          0.        ]
 [ 0.          1.53910055  0.67839033  0.24117016]
 [ 0.          0.          0.          2.36505763]
 [ 0.26202877  0.87039664  0.          0.51390909]
 [ 0.3097436   0.          0.          0.76477119]
 [ 0.          0.          1.25928933  0.48848648]]


### 아래는 행렬곱과 행렬의 transpose를 구현한 것이다. 
1. 행렬곱은 np.dot에서 가져온 것임.
```python
np.dot(A,B)
```
2. 앞의 행렬의 열과 뒤의 행렬의 행이 맞아야지만 곱이 성사되고, 안 되면 에러를 던짐.

In [27]:
data = np.array([[1,2,3], [4,5,6]])
data1 = np.array([[1,2],[3,4],[5,6]])
result = dot(data, data1)
print(result)
print(result.T)

[[22 28]
 [49 64]]
[[22 49]
 [28 64]]


### matlab 형식의 : 키워드도 사용가능하다.
1. 단 인덱스는 파이썬 인덱스이므로 0부터 시작한다,
2. 뒤의 2는 해당 index를 포함 안하고 이전까지만.
    * 아래는 2행 이전까지, 그리고 2열포함 이후부터를 의미함

In [36]:
a = np.array([[1,2,3,4,5], [4,5,6,7,8], [14,15,16,17,18]])
print(a)
a[:2,2:];
a[:2,2:] = 'hello'
print(a)


[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [14 15 16 17 18]]


ValueError: invalid literal for int() with base 10: 'hello'